# Generated by Django 6.0.7 on 2026-08-03 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(help_text='Unique identifier / unit number for the truck.', max_length=20)),
                ('trailer_id', models.CharField(blank=True, help_text='Trailer identifier, if applicable.', max_length=20, null=True)),
                ('alignment_date', models.DateField(help_text='Date the alignment service was performed.')),
                ('alignment_time', models.TimeField(help_text='Time the alignment service was performed.')),
                ('mileage', models.IntegerField(help_text='Odometer reading (miles) at time of service.', validators=[django.core.validators.MinValueValidator(1, message='Mileage must be a positive number.')])),
                ('tech_name', models.CharField(help_text='Name of the technician who performed the alignment.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alignment',
                'verbose_name_plural': 'Alignments',
                'ordering': ['-alignment_date', '-alignment_time'],
            },
        ),
    ]
