# Generated by Django 4.2.30 on 2026-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=20, unique=True)),
                ('trailer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to retire a unit from the dropdowns.')),
            ],
            options={
                'verbose_name': 'Fleet Truck',
                'verbose_name_plural': 'Fleet Trucks',
                'ordering': ['truck_id'],
            },
        ),
    ]
