# Generated by Django 4.2.30 on 2026-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0003_seed_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='current_odometer',
            field=models.PositiveIntegerField(blank=True, help_text='Most recent known odometer reading (KM). Kept in sync by Service Tracking mileage updates.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_service_km',
            field=models.PositiveIntegerField(blank=True, help_text="Odometer reading (KM) at the truck's most recent service.", null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='service_interval_km',
            field=models.PositiveIntegerField(default=15000, help_text='KM between scheduled preventive services for this unit.'),
        ),
    ]
