# Generated by Django 4.2.30 on 2026-08-21 10:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alignments', '0004_truck_current_odometer_truck_last_service_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('approaching', 'Vehicle Approaching Service'), ('due_soon', 'Vehicle Due Soon'), ('overdue', 'Vehicle Overdue'), ('stale_mileage', 'Mileage Not Updated')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('in_system', 'In-System')], max_length=10)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approaching_km_remaining', models.PositiveIntegerField(default=3000)),
                ('due_soon_km_remaining', models.PositiveIntegerField(default=1000)),
                ('stale_mileage_days', models.PositiveIntegerField(default=14)),
            ],
            options={
                'verbose_name': 'Service Threshold Settings',
                'verbose_name_plural': 'Service Threshold Settings',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.CharField(blank=True, max_length=30)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('trailer', 'Trailer'), ('truck_trailer', 'Truck & Trailer'), ('van', 'Van'), ('pickup', 'Pickup'), ('other', 'Other')], default='truck', max_length=20)),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='service_tracking.customer')),
                ('truck', models.OneToOneField(help_text='Links this service profile to the fleet register entry used by Alignment Tracker.', on_delete=django.db.models.deletion.PROTECT, related_name='service_vehicle', to='alignments.truck')),
            ],
            options={
                'ordering': ['truck__truck_id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('odometer_reading', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('service_type', models.CharField(choices=[('preventive', 'Preventive Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('other', 'Other')], default='preventive', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('parts_used', models.TextField(blank=True)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('next_service_km', models.PositiveIntegerField(blank=True, help_text='Snapshot of the next-due KM at the time this service was recorded.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='service_tracking.vehicle')),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_contacted', 'Not Contacted'), ('called', 'Called'), ('confirmed', 'Customer Confirmed'), ('scheduled', 'Appointment Scheduled'), ('arrived', 'Vehicle Arrived'), ('in_progress', 'Service In Progress'), ('completed', 'Service Completed'), ('declined', 'Customer Declined'), ('rescheduled', 'Rescheduled')], default='not_contacted', max_length=20)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_method', models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('in_person', 'In Person')], max_length=10)),
                ('person_contacted', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='service_tracking.vehicle')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.TextField(blank=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_tracking.notificationrule')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='service_tracking.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MileageUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_reading', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recorded_date', models.DateField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('wialon', 'Wialon')], default='manual', max_length=10)),
                ('flagged_suspicious', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_updates', to='service_tracking.vehicle')),
            ],
            options={
                'ordering': ['-recorded_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=20)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
